/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gnu_readline_Readline */

#ifndef _Included_org_gnu_readline_Readline
#define _Included_org_gnu_readline_Readline
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gnu_readline_Readline
 * Method:    initReadlineImpl
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_gnu_readline_Readline_initReadlineImpl
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_gnu_readline_Readline
 * Method:    cleanupReadlineImpl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gnu_readline_Readline_cleanupReadlineImpl
  (JNIEnv *, jclass);

/*
 * Class:     org_gnu_readline_Readline
 * Method:    hasTerminalImpl
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_gnu_readline_Readline_hasTerminalImpl
  (JNIEnv *, jclass);

/*
 * Class:     org_gnu_readline_Readline
 * Method:    readlineImpl
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_gnu_readline_Readline_readlineImpl
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_gnu_readline_Readline
 * Method:    addToHistoryImpl
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_gnu_readline_Readline_addToHistoryImpl
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_gnu_readline_Readline
 * Method:    getHistoryImpl
 * Signature: (Ljava/util/Collection;)V
 */
JNIEXPORT void JNICALL Java_org_gnu_readline_Readline_getHistoryImpl
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_gnu_readline_Readline
 * Method:    getHistorySizeImpl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_gnu_readline_Readline_getHistorySizeImpl
  (JNIEnv *, jclass);

/*
 * Class:     org_gnu_readline_Readline
 * Method:    getHistoryLineImpl
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_gnu_readline_Readline_getHistoryLineImpl
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_gnu_readline_Readline
 * Method:    clearHistoryImpl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gnu_readline_Readline_clearHistoryImpl
  (JNIEnv *, jclass);

/*
 * Class:     org_gnu_readline_Readline
 * Method:    readInitFileImpl
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_gnu_readline_Readline_readInitFileImpl
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_gnu_readline_Readline
 * Method:    getLineBufferImpl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_gnu_readline_Readline_getLineBufferImpl
  (JNIEnv *, jclass);

/*
 * Class:     org_gnu_readline_Readline
 * Method:    parseAndBindImpl
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_gnu_readline_Readline_parseAndBindImpl
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_gnu_readline_Readline
 * Method:    readHistoryFileImpl
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_gnu_readline_Readline_readHistoryFileImpl
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_gnu_readline_Readline
 * Method:    writeHistoryFileImpl
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_gnu_readline_Readline_writeHistoryFileImpl
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_gnu_readline_Readline
 * Method:    setCompleterImpl
 * Signature: (Lorg/gnu/readline/ReadlineCompleter;)V
 */
JNIEXPORT void JNICALL Java_org_gnu_readline_Readline_setCompleterImpl
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_gnu_readline_Readline
 * Method:    getWordBreakCharactersImpl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_gnu_readline_Readline_getWordBreakCharactersImpl
  (JNIEnv *, jclass);

/*
 * Class:     org_gnu_readline_Readline
 * Method:    setWordBreakCharactersImpl
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_gnu_readline_Readline_setWordBreakCharactersImpl
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
